spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      primary: mysql    #设置默认的数据源为 Mysql
      strict: true      #设置严格模式,启动后在未匹配到指定数据源时候会抛出异常
      druid:
        initial-size: 2 # 初始化连接数目
        max-active: 10  # 最大活跃连接数
        min-idle: 2     # 最小空闲连接数
        max-wait: 5000  # 最长连接等待时间
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        oracle:
          url: jdbc:oracle:thin:@//localhost:1521/orcl
          username: C##KULUO
          password: 123456
          driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 8080
