server:
  port: 8080

spring:
  datasource:
    druid:
      mysql:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
        username: root
        password: root
        initial-size: 1   # MySQL 初始化连接数目
        max-active: 20    # MySQL 最大活跃连接数
        max-wait: 5000    # MySQL 最长连接等待时间
        min-idle: 1       # MySQL 最小空闲连接数
      oracle:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@//localhost:1521/orcl
        username: C##KULUO
        password: 123456
        initial-size: 1   # Oracle 初始化连接数目
        max-active: 20    # Oracle 最大活跃连接数
        max-wait: 5000    # Oracle 最长连接等待时间
        min-idle: 1       # Oracle 最小空闲连接数
